goog.provide('openllm.components.side_bar.model_params.subs');
/**
 * Maps paramter ids to human readable names.
 */
openllm.components.side_bar.model_params.subs.parameter_id__GT_human_readable = cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"top_k","top_k",-591681887),new cljs.core.Keyword(null,"encoder_repetition_penalty","encoder_repetition_penalty",888986818),new cljs.core.Keyword(null,"epsilon_cutoff","epsilon_cutoff",1555534979),new cljs.core.Keyword(null,"num_beam_groups","num_beam_groups",-357601117),new cljs.core.Keyword(null,"penalty_alpha","penalty_alpha",-145881435),new cljs.core.Keyword(null,"diversity_penalty","diversity_penalty",2103037574),new cljs.core.Keyword(null,"top_p","top_p",297346822),new cljs.core.Keyword(null,"max_new_tokens","max_new_tokens",-1513269080),new cljs.core.Keyword(null,"num_beams","num_beams",187599721),new cljs.core.Keyword(null,"max_time","max_time",-981431349),new cljs.core.Keyword(null,"typical_p","typical_p",-752884212),new cljs.core.Keyword(null,"use_cache","use_cache",-1524453008),new cljs.core.Keyword(null,"eta_cutoff","eta_cutoff",-586230415),new cljs.core.Keyword(null,"early_stopping","early_stopping",940248339),new cljs.core.Keyword(null,"repetition_penalty","repetition_penalty",-2138859435),new cljs.core.Keyword(null,"min_length","min_length",-968562827),new cljs.core.Keyword(null,"length_penalty","length_penalty",882966168),new cljs.core.Keyword(null,"temperature","temperature",899018429),new cljs.core.Keyword(null,"min_new_tokens","min_new_tokens",-1806294754)],["Top K","Encoder Repetition Penalty","Epsilon Cutoff","Number of Beam Groups","Penalty Alpha","Diversity Penalty","Top P","Maximum New Tokens","Number of Beams","Maximum Time","Typical P","Use Cache","Eta Cutoff","Early Stopping","Repetition Penalty","Minimum Length","Length Penalty","Temperature","Minimum New Tokens"]);
re_frame.core.reg_sub.cljs$core$IFn$_invoke$arity$variadic(new cljs.core.Keyword("openllm.components.side-bar.model-params.subs","model-config","openllm.components.side-bar.model-params.subs/model-config",2080539653),cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"<-","<-",760412998),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.side-bar.subs","model-params-db","openllm.components.side-bar.subs/model-params-db",627352530)], null),(function (model_params_db,_){
return model_params_db;
})], 0));
re_frame.core.reg_sub.cljs$core$IFn$_invoke$arity$variadic(new cljs.core.Keyword("openllm.components.side-bar.model-params.subs","human-readable-config","openllm.components.side-bar.model-params.subs/human-readable-config",215692576),cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([new cljs.core.Keyword(null,"<-","<-",760412998),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.side-bar.model-params.subs","model-config","openllm.components.side-bar.model-params.subs/model-config",2080539653)], null),(function (model_config,_){
return cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2((function (p__30382){
var vec__30383 = p__30382;
var k = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__30383,(0),null);
var v = cljs.core.nth.cljs$core$IFn$_invoke$arity$3(vec__30383,(1),null);
return new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [k,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"name","name",1843675177),(openllm.components.side_bar.model_params.subs.parameter_id__GT_human_readable.cljs$core$IFn$_invoke$arity$1 ? openllm.components.side_bar.model_params.subs.parameter_id__GT_human_readable.cljs$core$IFn$_invoke$arity$1(k) : openllm.components.side_bar.model_params.subs.parameter_id__GT_human_readable.call(null,k)),new cljs.core.Keyword(null,"value","value",305978217),v], null)], null);
}),model_config));
})], 0));

//# sourceMappingURL=openllm.components.side_bar.model_params.subs.js.map
