goog.provide('openllm.components.side_bar.views');
/**
 * The collapse side bar button. It changes its icon depending on whether
 * the side bar is collapsed or not.
 */
openllm.components.side_bar.views.collapse_side_bar_button = (function openllm$components$side_bar$views$collapse_side_bar_button(){
var tooltip_text_collapse_sidebar = re_frame.core.subscribe.cljs$core$IFn$_invoke$arity$1(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.side-bar.subs","tooltip-text-collapse-sidebar","openllm.components.side-bar.subs/tooltip-text-collapse-sidebar",-949577152)], null));
var collapse_icon = re_frame.core.subscribe.cljs$core$IFn$_invoke$arity$1(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.side-bar.subs","collapse-icon","openllm.components.side-bar.subs/collapse-icon",372002502)], null));
return (function (){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"class","class",-2030961996),"-ml-4"], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [reagent_mui.material.tooltip.tooltip,new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"title","title",636505583),cljs.core.deref(tooltip_text_collapse_sidebar)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [reagent_mui.material.button.button,new cljs.core.PersistentArrayMap(null, 4, [new cljs.core.Keyword(null,"on-click","on-click",1632826543),(function (){
return re_frame.core.dispatch(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.side-bar.events","toggle-side-bar","openllm.components.side-bar.events/toggle-side-bar",209449458)], null));
}),new cljs.core.Keyword(null,"color","color",1011675173),"secondary",new cljs.core.Keyword(null,"class","class",-2030961996),"h-4",new cljs.core.Keyword(null,"style","style",-496642736),new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"max-width","max-width",-1939924051),"16px",new cljs.core.Keyword(null,"min-width","min-width",1926193728),"16px",new cljs.core.Keyword(null,"background-color","background-color",570434026),"black",new cljs.core.Keyword(null,"border-radius","border-radius",419594011),"8px 0px 0px 8px",new cljs.core.Keyword(null,"margin-top","margin-top",392161226),"-2px"], null)], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"class","class",-2030961996),"-mr-1 -mt-px"], null),cljs.core.deref(collapse_icon)], null)], null)], null)], null);
});
});
/**
 * The sidebar wrapped with a Material UI Collapse component. The collapse
 * component is used to animate the sidebar when it is opened or closed.
 */
openllm.components.side_bar.views.side_bar_with_mui_collapse = (function openllm$components$side_bar$views$side_bar_with_mui_collapse(){
var side_bar_open_QMARK_ = re_frame.core.subscribe.cljs$core$IFn$_invoke$arity$1(new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.side-bar.subs","side-bar-open?","openllm.components.side-bar.subs/side-bar-open?",1372785530)], null));
return (function (){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [reagent_mui.material.collapse.collapse,new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"in","in",-1531184865),cljs.core.deref(side_bar_open_QMARK_),new cljs.core.Keyword(null,"orientation","orientation",623557579),"horizontal",new cljs.core.Keyword(null,"class","class",-2030961996),"flex flex-col w-80"], null),new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"class","class",-2030961996),"flex flex-col w-80 h-full border-l border-gray-200 pt-0.5 pb-4"], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [openllm.components.side_bar.model_selection.views.model_selection], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"hr","hr",1377740067),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"class","class",-2030961996),"mb-2 border-1 border-gray-200"], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [openllm.components.common.views.headline,"Parameters"], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"class","class",-2030961996),"my-0 h-0 flex-1 flex flex-col overflow-y-auto scrollbar"], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"class","class",-2030961996),"px-3 mt-0 relative inline-block text-left"], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [openllm.components.side_bar.model_params.views.parameter_list], null)], null)], null)], null)], null);
});
});
/**
 * The render function of the toolbar on the very right of the screen. Contains the
 * model selection dropdowns and the parameter list.
 */
openllm.components.side_bar.views.side_bar = (function openllm$components$side_bar$views$side_bar(){
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"<>","<>",1280186386),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [openllm.components.side_bar.views.collapse_side_bar_button], null),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"div","div",1057191632),new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"class","class",-2030961996),"hidden lg:flex lg:flex-shrink-0"], null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [openllm.components.side_bar.views.side_bar_with_mui_collapse], null)], null)], null);
});

//# sourceMappingURL=openllm.components.side_bar.views.js.map
