goog.provide('openllm.db');
cljs.spec.alpha.def_impl(new cljs.core.Keyword("openllm.db","screen-id","openllm.db/screen-id",-1047327490),new cljs.core.Symbol("cljs.core","keyword?","cljs.core/keyword?",713156450,null),cljs.core.keyword_QMARK_);
cljs.spec.alpha.def_impl(new cljs.core.Keyword("openllm.db","db","openllm.db/db",2117056544),cljs.core.list(new cljs.core.Symbol("cljs.spec.alpha","keys","cljs.spec.alpha/keys",1109346032,null),new cljs.core.Keyword(null,"req-un","req-un",1074571008),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.db","components-db","openllm.components.db/components-db",889064542),new cljs.core.Keyword("openllm.db","screen-id","openllm.db/screen-id",-1047327490)], null)),cljs.spec.alpha.map_spec_impl(cljs.core.PersistentHashMap.fromArrays([new cljs.core.Keyword(null,"req-un","req-un",1074571008),new cljs.core.Keyword(null,"opt-un","opt-un",883442496),new cljs.core.Keyword(null,"gfn","gfn",791517474),new cljs.core.Keyword(null,"pred-exprs","pred-exprs",1792271395),new cljs.core.Keyword(null,"keys-pred","keys-pred",858984739),new cljs.core.Keyword(null,"opt-keys","opt-keys",1262688261),new cljs.core.Keyword(null,"req-specs","req-specs",553962313),new cljs.core.Keyword(null,"req","req",-326448303),new cljs.core.Keyword(null,"req-keys","req-keys",514319221),new cljs.core.Keyword(null,"opt-specs","opt-specs",-384905450),new cljs.core.Keyword(null,"pred-forms","pred-forms",172611832),new cljs.core.Keyword(null,"opt","opt",-794706369)],[new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.db","components-db","openllm.components.db/components-db",889064542),new cljs.core.Keyword("openllm.db","screen-id","openllm.db/screen-id",-1047327490)], null),null,null,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [(function (G__28499){
return cljs.core.map_QMARK_(G__28499);
}),(function (G__28499){
return cljs.core.contains_QMARK_(G__28499,new cljs.core.Keyword(null,"components-db","components-db",502469729));
}),(function (G__28499){
return cljs.core.contains_QMARK_(G__28499,new cljs.core.Keyword(null,"screen-id","screen-id",9826069));
})], null),(function (G__28499){
return ((cljs.core.map_QMARK_(G__28499)) && (((cljs.core.contains_QMARK_(G__28499,new cljs.core.Keyword(null,"components-db","components-db",502469729))) && (cljs.core.contains_QMARK_(G__28499,new cljs.core.Keyword(null,"screen-id","screen-id",9826069))))));
}),cljs.core.PersistentVector.EMPTY,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("openllm.components.db","components-db","openllm.components.db/components-db",889064542),new cljs.core.Keyword("openllm.db","screen-id","openllm.db/screen-id",-1047327490)], null),null,new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"components-db","components-db",502469729),new cljs.core.Keyword(null,"screen-id","screen-id",9826069)], null),cljs.core.PersistentVector.EMPTY,new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","map?","cljs.core/map?",-1390345523,null),new cljs.core.Symbol(null,"%","%",-950237169,null))),cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","contains?","cljs.core/contains?",-976526835,null),new cljs.core.Symbol(null,"%","%",-950237169,null),new cljs.core.Keyword(null,"components-db","components-db",502469729))),cljs.core.list(new cljs.core.Symbol("cljs.core","fn","cljs.core/fn",-1065745098,null),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"%","%",-950237169,null)], null),cljs.core.list(new cljs.core.Symbol("cljs.core","contains?","cljs.core/contains?",-976526835,null),new cljs.core.Symbol(null,"%","%",-950237169,null),new cljs.core.Keyword(null,"screen-id","screen-id",9826069)))], null),null])));
/**
 * What gets put into app-db by default. This is the very root of the `app-db`.
 * See `core.cljs` for `(dispatch-sync [:initialise-db])` and 'events.cljs'
 * for the registration of `:initialise-db` effect handler.
 */
openllm.db.default_db = new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"components-db","components-db",502469729),openllm.components.db.initial_db(),new cljs.core.Keyword(null,"screen-id","screen-id",9826069),new cljs.core.Keyword(null,"playground","playground",688158191)], null);

//# sourceMappingURL=openllm.db.js.map
